In [4]:
from data_distribution_n import find_distributions
import pandas as pd
df = pd.read_csv('./data/churn.csv')

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
find_distributions(df, top_n=3)

,feature,data_type,best_distribution,parameters,goodness_of_fit,candidates
0,customerID,categorical/text,Categorical,{'unique_values': 7043},0.000000,[Categorical (text/ID field)]
1,gender,categorical/text,Categorical,{'unique_values': 2},0.000000,[Categorical (text/ID field)]
2,SeniorCitizen,binary,bernoulli,{'p': 0.1621468124378816},0.000000,[bernoulli (fit: 0.0000)]
3,Partner,categorical/text,Categorical,{'unique_values': 2},0.000000,[Categorical (text/ID field)]
4,Dependents,categorical/text,Categorical,{'unique_values': 2},0.000000,[Categorical (text/ID field)]
5,tenure,discrete_count,geometric,{'p': 0.030891705776569148},8621.831457,"[geometric (fit: 8621.8315), nbinom (fit: 1362..."
6,PhoneService,categorical/text,Categorical,{'unique_values': 2},0.000000,[Categorical (text/ID field)]
7,MultipleLines,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
8,InternetService,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
9,OnlineSecurity,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
10,OnlineBackup,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
11,DeviceProtection,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
12,TechSupport,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
13,StreamingTV,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
14,StreamingMovies,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
15,Contract,categorical/text,Categorical,{'unique_values': 3},0.000000,[Categorical (text/ID field)]
16,PaperlessBilling,categorical/text,Categorical,{'unique_values': 2},0.000000,[Categorical (text/ID field)]
17,PaymentMethod,categorical/text,Categorical,{'unique_values': 4},0.000000,[Categorical (text/ID field)]
18,MonthlyCharges,continuous,gamma,"{'param0': 320.5369517006978, 'param1': -478.5...",0.125827,"[gamma (fit: 0.1258), lognorm (fit: 0.1262), w..."
19,TotalCharges,continuous,gamma,"{'param0': 0.6630487058453226, 'param1': 18.79...",0.054344,"[gamma (fit: 0.0543), weibull_min (fit: 0.0755..."
20,Churn,categorical/text,Categorical,{'unique_values': 2},0.000000,[Categorical (text/ID field)]